bootdevcan/config/routes.rb
Bootdevcan::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index', as: :authenticated_root
  end
  root :to => "home#index"

  devise_for :users

end

bootdevcan/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new #guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
  end
end

bootdevcan/app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

bootdevcan/app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false

end

bootdevcan/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
end

bootdevcan/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @users = User.all
  end

end

bootdevcan/app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">$#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

bootdevcan/app/helpers/home_helper.rb
module HomeHelper
end

bootdevcan/app/views/home/index.html.erb
<h1>Home Index</h1>
<% @users.each do |user| %>
  <p>User: <%= user.name %></p>
<% end %>

bootdevcan/app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
      <%= link_to 'Home', root_path %>
      <%= link_to 'About', page_path('about') %>
    </div>
    <div class="text-right col-lg-6 col-md-6 col-sm-6 col-xs-6">
      <p>Created by <a href="https://github.com/alvinang" class="orange">© BootDevCan, 2013.</a></p>
    </div>
  </div>
</footer>

bootdevcan/app/views/layouts/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "BootDevCan" %></title>
  <meta name="description" content="<%= content_for?(:title) ? yield(:title) : "Bootstrap-Devise-Cancan integration on a Rails App" %>">
  <%= csrf_meta_tags %>

  <!-- Styles -->
  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <!--<#%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>-->

  <!-- Javascripts -->
  <%= javascript_include_tag "application" %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>

</head>

bootdevcan/app/views/layouts/_navigation.html.erb
<header class="navbar navbar-default navbar-inverse" role="navigation" style="margin-bottom:0;">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'BootDevCan', root_path, class: 'navbar-brand' %>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to('Edit account', edit_user_registration_path) %></li>
          <% if current_user.has_role? :admin %>
            <li><%= link_to('Admin', users_path) %></li>
          <% end %>
          <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
        <% else %>
          <li><%= link_to('Login', new_user_session_path) %></li>
          <li><%= link_to('Sign up', new_user_registration_path) %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

bootdevcan/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render :partial => 'layouts/head' %></head>
<body>
  <%= render :partial => 'layouts/navigation' %>

  <div id="main" role="main">
    <div class="container">
      <div class="content">
        <div class="row">
          <div class="span12">

            <%= yield %>
          </div>
        </div>
      </div>
    </div>

  </div>

  <%= render :partial => 'layouts/footer' %>
</body>
</html>

bootdevcan/app/views/pages/about.html.erb
<h1>About Us</h1>